### ISSUE TITLE
Can't reshare - URL too long

### ISSUE THREAD

**Issue by igordejanovic** [textX/textx-playground#3]
I was playing today with the new examples and visualization functionality and noticed one bug. It's maybe a nit picking but I noticed that if I create a share link and go to it I can't reshare. 

For example, if I get a link from someone and do a few changes and want to create a new one. Clicking on share button reports that sharing is not possible as the URL is too long. I guess that the share action tries to tackle a new grammar/model on the existing link which already has one. Maybe there is a way to replace the existing query parameters if they are grammar/model.

Other then this little issue the playground really looks and works great!
Excellent work @AirmiX !

**Comment by AirmiX** [comment]
Thank you @igordejanovic!

And great catch! The issue was exactly the one you described. It is fixed in [this commit](https://github.com/textX/textx-playground/pull/4/commits/8a300759bf5e806f2a677d82e0e7055c36388f73).

**Comment by igordejanovic** [comment]
Thanks. I verify that the problem has been fixed.
